version: "2.2"

services:
  ping-server:
    container_name: ping-server
    ports:
      - "8080:8080"
    build:
      context: ./src/Dockerfile
    restart: unless-stopped

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "30:30"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ping-server

