version: "2.2"

services:
  ping-server:
    container_name: ping-server
    ports:
      - "8080:8080"
    image: test9:image
    build:
      dockerfile: src/Dockerfile
    restart: unless-stopped

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "30:30"
    volumes:
      - /home/rnd/IdeaProjects/APIping/nginx/default.conf

