version: "3"

services:
  nginx:
    container_name: nginx-server
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "30:30"
    depends_on:
      - ping-server
    networks:
      - nginx-networks
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  nginx-networks:
    name: nginx-networks
    driver: bridge
    
